# Generated by Django 2.0 on 2018-04-10 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w\\s\\-]+$', 'Letters, numbers, spaces and or - are allowed')])),
                ('message', models.TextField(max_length=10000, validators=[django.core.validators.RegexValidator('^[\\w\\d\\s\\t\\n\\r\\!\\@\\#\\$\\%\\(\\)\\\\_\\+\\-\\=\\?\\<\\>\\,\\.\\:\\&//]+$', 'Letters, numbers, spaces, new lines and or !@#$%&()-_+=:<>?/,. are allowed')])),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('responded_to', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Me Submissions',
                'db_table': 'contact_me',
                'ordering': ['time_submitted', 'responded_to'],
            },
        ),
    ]
